# GitHub Pages configuration
title: "HMRC Tax Return Calculator"
description: "Calculate your UK income tax refund with Telegram integration"
url: "https://yourusername.github.io"
baseurl: "/your-repository-name"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - node_modules/
  - vendor/